version: '3.8'

services:
  app:
    environment:
      NODE_ENV: production
    # Remove pgAdmin for production
    restart: always
    
  postgres:
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-craftsman_service}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    # Don't expose postgres port in production for security
    ports: []
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod:
    driver: local
